import { ObjectDefinitions, type ObjectDefinition } from "../utils/objectDefinitions";

export interface EmoteDefinition extends ObjectDefinition {}

export const Emotes = ObjectDefinitions.create<EmoteDefinition>()(
    () => ({
        emote_factory: (name: string) => ({
            idString: name.toLowerCase().replace(/ /g, "_"),
            name
        })
    })
)(
    apply => [
        "Happy Face",
        "Sad Face",
        "Thumbs Up",
        "Thumbs Down",
        "Disappointed Face",
        "Sobbing Face",
        "Angry Face",
        "Heart Face",
        "Joyful Face",
        "Cool Face",
        "Upside Down Face",
        "Picasso Face",
        "Alien",
        "Headshot",
        "Dab",
        "Devil Face",
        "Bandaged Face",
        "Cold Face",
        "Thinking Face",
        "Nervous Face",
        "Sweating Face",
        "Greedy Face",
        "Creepy Clown",
        "Lying Face",
        "Suroi Logo",
        "AEGIS Logo",
        "Flint Logo",
        "Team = Ban",
        "gg",
        "ez",
        "Duel",
        "Question Mark",
        "Skull",
        "Troll Face",
        "Clueless",
        "Pog",
        "Froog",
        "Bleh",
        "Fire",
        "RIP",
        "Monkey",
        "Carrot",
        "Tomato",
        "Egg",
        "Squid",
        "Wave",
        "Melting Face",
        "Grimacing Face",
        "Vomiting Face",
        "Screaming Face",
        "Pleading Face",
        "Sad Smiling Face",
        "Triumphant Face",
        "Questioning Face",
        "Smirking Face",
        "Blushing Face",
        "Saluting Face",
        "Neutral Face",
        "Relieved Face",
        "Monocle Face",
        "Partying Face",
        "Shushing Face",
        "Zipper Mouth Face",
        "Sighing Face",
        "Chicken Dinner"
    ].map(name => apply("emote_factory", {}, name))
);
